# Generated by Django 5.2.3 on 2025-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_profile_is_approved_post_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_approved',
            field=models.IntegerField(choices=[(0, 'Not Approved'), (1, 'Approved'), (2, 'Processed')], default=0),
        ),
    ]
